apiVersion: apps/v1
kind: Deployment
metadata:
  name: development-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dev-app
  template:
    metadata:
      labels:
        app: dev-app
    spec:
      containers:
      - name: us-east1-docker.pkg.dev/qwiklabs-gcp-00-34cd3ea35b43/my-repository/hello-cloudbuild:v1.0
        image: 
        ports:
        - containerPort: 8080
